name:                retroclash-lib
version:             0.1.2.2
category:            Hardware
synopsis:            Code shared across the code samples in the book "Retrocomputing with Clash"
description: |
  Clash components useful when implementing, or interfacing with,
  retro-computers:
    
    * UART
    
    * Multi-digit seven-segment display driver
    
    * Keypad matrix scanner
    
    * PS/2 keyboard driver
    
    * VGA signal generator

    * Video coordinate transformers
    
    * A framework for monadic CPU descriptions
    
    * Address maps
    
    * Various small utilities
    
homepage:            https://unsafePerform.IO/retroclash/
github:              gergoerdi/retroclash-lib
license:             MIT
author:              Gergő Érdi
maintainer:          gergo@erdi.hu
copyright:           2021 Gergő Érdi


dependencies:
  - base >= 4.14 && < 5
  - clash-prelude >= 1.4.2 && < 2.0
  - clash-lib  >= 1.4.2 && < 2.0
  - clash-ghc >= 1.4.2 && < 2.0
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - mtl
  - transformers
  - barbies ^>= 2.0.1
  - lens
  - containers
  - template-haskell
  - th-orphans >= 0.13.11
  - lift-type ^>= 0.1
  - monoidal-containers ^>= 0.6

source-dirs:
  - src

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

library:
  exposed-modules:
    - RetroClash.Utils
    - RetroClash.Clock
    - RetroClash.Barbies
    - RetroClash.Keypad
    - RetroClash.SevenSegment
    - RetroClash.SerialRx
    - RetroClash.SerialTx
    - RetroClash.I2C
    - RetroClash.VGA
    - RetroClash.Video
    - RetroClash.CPU
    - RetroClash.Delayed
    - RetroClash.Stack
    - RetroClash.BCD
    - RetroClash.Port
    - RetroClash.PS2
    - RetroClash.PS2.ASCII
    - RetroClash.Memory
